#!/usr/bin/env bash

NOW=$(date +"%Y%m%d%H%M%S")
SRC_DIR=$(pwd)/dotfiles
DST_DIR=${HOME}
BKP_DIR=${DST_DIR}/.mylinux/${NOW}

stream() {
    for v in $@; do
      echo $v
    done
}

pipe() {
  while read data; do
    (eval "echo $(echo $@)")
	  if [ -z "$DEBUG" ]; then
      (eval "$(echo $@)")
	  fi
  done
}

create_directory() {
  pipe "mkdir -p \$data"
}

list_dotfiles() {
  stream $(find ./dotfiles -maxdepth 1 | cut -d "/" -f 3 | grep -Ev "^(|\.config)$")
  stream $(find ./dotfiles/.config -maxdepth 1 | cut -d "/" -f 3,4 | grep -Ev "^(|\.config)$")
}

backup() {
  pipe mv ${DST_DIR}/\$data ${BKP_DIR}/\$data
}

link() {
  pipe ln -s ${SRC_DIR}/\$data ${DST_DIR}/\$data
}

stream $DST_DIR/.config $BKP_DIR/.config | create_directory

list_dotfiles | backup

list_dotfiles | link

echo '[[ -f ~/.mylinuxrc ]] && . ~/.mylinuxrc' >> ${DST_DIR}/.bashrc
. ${DST_DIR}/.bashrc

echo '
if [ -z "$DISPLAY" -a $XDG_VTNR -eq 1 ]; then
  startx && exit
fi' >> ${DST_DIR}/.bash_profile


curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py --user
rm get-pip.py
pip install -U pynvim
pip install -U pyvim
pip install -U pygments
pip install -U pipenv
pip install -U notedown
pip install -U pylint
pip install -U yapf
pip install -U autoflake
pip install -U isort
pip install -U coverage
pip install -U python-language-server
pip install -U pillow

npm config set prefix ${DST_DIR}/.local
npm i -g typescript
npm i -g lehre
npm i -g remark
npm i -g remark-cli
npm i -g remark-stringify
npm i -g remark-frontmatter
npm i -g wcwidth
npm i -g prettier
npm i -g bash-language-server
npm i -g vscode-css-languageserver-bin
npm i -g vscode-html-languageserver-bin
npm i -g javascript-typescript-langserver

go get -u golang.org/x/tools/gopls@latest

curl -sLf https://spacevim.org/install.sh | bash
cd ${DST_DIR}/.SpaceVim/bundle/vimproc.vim
make
cd -

