#!/usr/bin/env sh



if [ "$XDG_CURRENT_DESKTOP" = "sway" ]; then
    filter=$($MSG_PROGRAM -t get_tree | jq -r "[.nodes[].nodes[] | {ws: .num, id: .nodes[].id, app_id: .nodes[].app_id, name: .nodes[].name}] | unique")
else
    filter=$()
fi


MENU=$(echo "$filter" | jq -r '.[] | "ws:"+(.ws|tostring)+"\\tid:"+(.id|tostring)+"\\t["+.app_id+"] "+.name')

echo "$MENU" | fzf | awk '{print $2}' | cut -d ":" -f 2 | xargs -I % "$MSG_PROGRAM" '[con_id="%"] focus'

