#!/bin/sh

source $HOME/.mylinuxrc

alias dmenu_shutdown="dmenu $DMENU_OPTS"

MENU_OPTS=' Shutdown\n Reboot\n Suspend\n Lock\n Logout'

RESULT=$(echo -e $MENU_OPTS | dmenu_shutdown)

if [[ $RESULT = " Shutdown" ]]; then
	systemctl poweroff
elif [[ $RESULT = " Reboot" ]]; then
	systemctl reboot
elif [[ $RESULT = " Suspend" ]]; then
	systemctl suspend
elif [[ $RESULT = " Lock" ]]; then
	~/.config/i3/scripts/blur-lock.sh
elif [[ $RESULT = " Logout" ]]; then
    $MSG_PROGRAM exit
fi

